version: '2'
services:
    mjpg-streamer:
      restart: always
      image: webcam-stream
      container_name: webcam-stream
      environment:
        - ENV_RESOLUTION=1280x720
        - ENV_FPS=30
      devices:
        - /dev/video0
      ports:
        - 8080:8080
